### ISSUE TITLE
Configure header elements of a request

### ISSUE THREAD

**Issue by sebastianneubert** [phmLabs/LiveTest2#42]
It should be possible to add special header data to the request object.

For example it should be possible to set the content_type of a request to application-xml.

```
# testsuite.yml
example:
    headers:
      - {Content-Type: 'application/xml'}
    Pages:
     - { url: /api/rest/users.json, post: { email: testuser@test.local, nickname: test, name: tester } }
```

The request to /api/rest/users.json should have the header:

```
'Content-Type: application/xml; charset=utf-8'
```
