### ISSUE TITLE
Update ZF2 (Zend\Http) Library

### ISSUE THREAD

**Issue by sebastianneubert** [phmLabs/LiveTest2#45]
Sometimes I get an error using following test:

```bash
     Url         :  http://www.livingathome.de/essen_geniessen/rezeptstrecken/
     Test        :  impressumPresent
     Test Class  :  LiveTest\TestCase\General\Html\TextPresent
     Session     :  top50
     Status      :  Error
     Message     :  Error parsing body - doesn't seem to be a chunked message
```

It seems, that there is an error with an older version of Zend/Http Library and Redirects. The given URL are redirected before they got the correct output. After calling the test twice, it works fine and the test pass.

*Configuration:*
```yaml
  impressumPresent:
    TestCase: LiveTest\TestCase\General\Html\TextPresent
    Parameter:
      text: 'Impressum'
    UseSessions:
     - redirectPage
```
